### PR TITLE
Update Makefile

### PR DESCRIPTION
**Pull request by priyankpat**
Changed the class name constructed by the jasmin to MyApp. The jasmin code creates MyApp on every build during the test.

### CODE REVIEW

**Comment by Probotect0r** [comment]
What's the point of this pull request? I thought she had different run commands for a reason so she could accommodate different cases.

**Comment by priyankpat** [comment]
The problem is everyone's jasmin file creates the same class name regardless the name of the file.So even if .j file name is different, the class name will still create MyApp.class

**Comment by Probotect0r** [comment]
You're right. I was trying to figure out how the name was chosen bit couldn't find anything.

**Comment by priyankpat** [comment]
Yep, so either everyone have to dynamically create class based on filename or keep the class name consistent and test with that name

**Comment by priyankpat** [comment]
Not needed, only need to pass one of the runs.

**Comment by adelehedrick** [comment]
Your code doesn't pass any of my run commands because no matter what you
are generating a class called "sample" which is not a case in the
assignment or ken's example posted

adele@adele-Surface-Pro-3:~/Desktop/Compilers_A3/100490143$ make all
java -jar ../lib/antlr-4.5.2-complete.jar -no-listener -no-visitor _.g4
javac -cp ../lib/antlr-4.5.2-complete.jar:../lib/jasmin.jar:. *.java
adele@adele-Surface-Pro-3:~/Desktop/Compilers_A3/100490143$ make run3
java -cp ../lib/antlr-4.5.2-complete.jar:../lib/jasmin.jar:. SimpleCompiler
< ../tests/declaration.txt > declaration.j
Error: Invalid use of command line argument, expected file name
java -jar ../lib/jasmin.jar declaration.j
declaration.j: JAS Error: empty source file.
declaration.j: Found 1 errors
java -cp . MyApp
Error: Could not find or load main class MyApp
Makefile:94: recipe for target 'run3' failed
make: *_\* [run3] Error 1
adele@adele-Surface-Pro-3:~/Desktop/Compilers_A3/100490143$ make clean
rm -rf SimpleLexer.java SimpleParser.java _.tokens *.class *.j
adele@adele-Surface-Pro-3:~/Desktop/Compilers_A3/100490143$ make all
java -jar ../lib/antlr-4.5.2-complete.jar -no-listener -no-visitor *.g4
javac -cp ../lib/antlr-4.5.2-complete.jar:../lib/jasmin.jar:. *.java
adele@adele-Surface-Pro-3:~/Desktop/Compilers_A3/100490143$ make run4
java -cp ../lib/antlr-4.5.2-complete.jar:../lib/jasmin.jar:. SimpleCompiler
< ../tests/declaration.txt > declaration.j
Error: Invalid use of command line argument, expected file name
java -jar ../lib/jasmin.jar declaration.j
declaration.j: JAS Error: empty source file.
declaration.j: Found 1 errors
java -cp . declaration
Error: Could not find or load main class declaration
Makefile:136: recipe for target 'run4' failed
make: *_\* [run4] Error 1
adele@adele-Surface-Pro-3:~/Desktop/Compilers_A3/100490143$ make clean
rm -rf SimpleLexer.java SimpleParser.java _.tokens *.class *.j
adele@adele-Surface-Pro-3:~/Desktop/Compilers_A3/100490143$ make run
java -cp ../lib/antlr-4.5.2-complete.jar:../lib/jasmin.jar:. SimpleCompiler
../tests/declaration.txt > declaration.j
Error: Could not find or load main class SimpleCompiler
Makefile:10: recipe for target 'run' failed
make: *_\* [run] Error 1
adele@adele-Surface-Pro-3:~/Desktop/Compilers_A3/100490143$ make all
java -jar ../lib/antlr-4.5.2-complete.jar -no-listener -no-visitor _.g4
javac -cp ../lib/antlr-4.5.2-complete.jar:../lib/jasmin.jar:. *.java
adele@adele-Surface-Pro-3:~/Desktop/Compilers_A3/100490143$ make run
java -cp ../lib/antlr-4.5.2-complete.jar:../lib/jasmin.jar:. SimpleCompiler
../tests/declaration.txt > declaration.j
java -jar ../lib/jasmin.jar declaration.j
Generated: sample.class
java -cp . MyApp
Error: Could not find or load main class MyApp
Makefile:10: recipe for target 'run' failed
make: *_\* [run] Error 1
adele@adele-Surface-Pro-3:~/Desktop/Compilers_A3/100490143$ make clean
rm -rf SimpleLexer.java SimpleParser.java _.tokens *.class *.j
adele@adele-Surface-Pro-3:~/Desktop/Compilers_A3/100490143$ make all
java -jar ../lib/antlr-4.5.2-complete.jar -no-listener -no-visitor *.g4
makjavac -cp ../lib/antlr-4.5.2-complete.jar:../lib/jasmin.jar:. *.java
e ruadele@adele-Surface-Pro-3:~/Desktop/Compilers_A3/100490143$ make run2
java -cp ../lib/antlr-4.5.2-complete.jar:../lib/jasmin.jar:. SimpleCompiler
../tests/declaration.txt > declaration.j
java -jar ../lib/jasmin.jar declaration.j
Generated: sample.class
java -cp . declaration
Error: Could not find or load main class declaration
Makefile:52: recipe for target 'run2' failed
make: *_\* [run2] Error 1
adele@adele-Surface-Pro-3:~/Desktop/Compilers_A3/100490143$

**Pull request closed without merging**
